### ISSUE TITLE
Got error under Silverstripe 3.1.5 

### ISSUE THREAD

**Issue by jason-zz** [silverstripe-archive/silverstripe-messagequeue#4]
Newsletter recommends this module. But it stops sending email out because the following error 'cli-script.php can't be run from a web request, you have to run it on the command-line.'

I debug it and found the below issue.

https://github.com/silverstripe-labs/silverstripe-messagequeue/blob/master/code/MessageQueue.php#L267

Currently, cli-script.php ( sake will call cli-script.php) only can be called from command line. 

Any ideas?

Thanks.

**Comment by jedateach** [comment]
Appears to be related to https://github.com/silverstripe-labs/silverstripe-newsletter/issues/85

**Comment by sunnysideup** [comment]
Thank you Jeremy for finding that link.
